# Generated by Django 5.2.16 on 2026-08-06 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('CRM Administrator', 'CRM Administrator'), ('Operations Manager', 'Operations Manager'), ('Sales Manager', 'Sales Manager'), ('Finance Manager', 'Finance Manager'), ('Business Analyst', 'Business Analyst')], max_length=100, unique=True)),
                ('assigned_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_team_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
