# Generated by Django 5.2.16 on 2026-08-09 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_seed_default_services'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='The authenticated user who actually performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='booking.booking'),
        ),
        migrations.AddField(
            model_name='notification',
            name='new_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='previous_value',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_CONFIRMATION', 'Booking Confirmation'), ('BOOKING_CANCELLATION', 'Booking Cancellation'), ('REMINDER', 'Reminder'), ('GENERAL', 'General'), ('BOOKING_CREATED', 'Booking Created'), ('BOOKING_UPDATED', 'Booking Updated'), ('BOOKING_RESCHEDULED', 'Booking Rescheduled'), ('WAITLIST_SLOT_AVAILABLE', 'Waitlist Slot Available')], default='GENERAL', max_length=50),
        ),
    ]
