# Generated by Django 5.2.16 on 2026-08-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_refund_reason_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='PAID', max_length=20),
        ),
    ]
