# Generated by Django 5.2.16 on 2026-08-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
