# Generated by Django 5.2.16 on 2026-08-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_service_booking_rate_snapshot_booking_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
