# Generated by Django 5.2.16 on 2026-08-26 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('role_assigned', 'Role assigned'), ('role_removed', 'Role removed'), ('invoice_created', 'Invoice created'), ('invoice_updated', 'Invoice updated'), ('invoice_deleted', 'Invoice deleted'), ('invoice_paid', 'Invoice marked paid'), ('invoice_unpaid', 'Invoice marked unpaid'), ('invoice_refunded', 'Invoice refunded'), ('client_created', 'Client created'), ('client_updated', 'Client updated'), ('client_deleted', 'Client deleted'), ('booking_cancelled', 'Booking cancelled'), ('booking_deleted', 'Booking deleted')], db_index=True, max_length=32)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='core_auditl_target__6c66b3_idx')],
            },
        ),
    ]
