# Generated by Django 5.2.16 on 2026-08-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('role_assigned', 'Role assigned'), ('role_removed', 'Role removed'), ('invoice_created', 'Invoice created'), ('invoice_updated', 'Invoice updated'), ('invoice_deleted', 'Invoice deleted'), ('invoice_paid', 'Invoice marked paid'), ('invoice_unpaid', 'Invoice marked unpaid'), ('invoice_refunded', 'Invoice refunded'), ('client_created', 'Client created'), ('client_updated', 'Client updated'), ('client_deleted', 'Client deleted'), ('booking_cancelled', 'Booking cancelled'), ('mfa_enabled', 'MFA enabled'), ('admin_seat_transferred', 'Admin seat transferred'), ('booking_deleted', 'Booking deleted')], db_index=True, max_length=32),
        ),
    ]
