# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - crm-booking-backend

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: crmbookingacr2026.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_CB958AE96D5B4C9088DA0CB980242F06 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_4FC2D1277BEF41FBBB0225314D2C5E8F }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: crmbookingacr2026.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_CB958AE96D5B4C9088DA0CB980242F06 }}/crm-booking-backend:${{ github.sha }}
          file: ./backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'crm-booking-backend'
          slot-name: 'Production'
          images: 'crmbookingacr2026.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_CB958AE96D5B4C9088DA0CB980242F06 }}/crm-booking-backend:${{ github.sha }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F89EB726FC414380AF50C661D0D1C1FC }}